In [2]:
import pandas as pd

# Cargar el archivo Excel
file_path = '/Users/luis/Desktop/00. UEV/Primero/00. Proyecto Análisis de Datos UE/Entrega 5/WDIEXCEL.xlsx'
excel_data = pd.ExcelFile(file_path)

In [3]:

# Leer la hoja específica "DATA"
df = pd.read_excel(excel_data, sheet_name='Data')

In [4]:

valores_unicos= df['Indicator Name'].unique()
df_valores_unicos = pd.DataFrame(valores_unicos, columns=['Unique Indicator Names'])
# Guardar los valores únicos en un archivo Excel
excel_file_path2 = '/Users/luis/Desktop/00. UEV/Primero/00. Proyecto Análisis de Datos UE/Entrega 5/valoresUnicos.xlsx'
df_valores_unicos.to_excel(excel_file_path2, sheet_name='Unicos', index=False)

print(f"Valores únicos guardados como Excel en: {excel_file_path2}")

Valores únicos guardados como Excel en: /Users/luis/Desktop/00. UEV/Primero/00. Proyecto Análisis de Datos UE/Entrega 5/valoresUnicos.xlsx

In [5]:
indicadores_valores_unicos = [

"Employment in agriculture (% of total employment) (modeled ILO estimate)",
"Employment in industry (% of total employment) (modeled ILO estimate)"
"Employment in services (% of total employment) (modeled ILO estimate)",
]

In [6]:
# Lista de indicadores relevantes
indicadores_relevantes = [
    "Unemployment, total (% of total labor force) (modeled ILO estimate)",
    #"Unemployment, total (% of total labor force) (national estimate)",
    "Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)",
    #"Unemployment, youth total (% of total labor force ages 15-24) (national estimate)",
    "Unemployment with advanced education (% of total labor force with advanced education)",
    "Unemployment with basic education (% of total labor force with basic education)",
    "Unemployment with intermediate education (% of total labor force with intermediate education)",
    "Labor force participation rate, total (% of total population ages 15+)",
    "Labor force participation rate, female (% of female population ages 15+)",
    "Labor force participation rate, male (% of male population ages 15+)",
    "Labor force, total",
    "Labor force, female (% of total labor force)",
    "Labor force, male (% of total labor force)",
    "Employment in agriculture (% of total employment) (modeled ILO estimate)",
    "Employment in industry (% of total employment) (modeled ILO estimate)",
    "Employment in services (% of total employment) (modeled ILO estimate)",
    "Employment to population ratio, 15+, total (%)",
    "Employment to population ratio, ages 15-24, total (%)",
    "GDP growth (annual %)",
    "GDP per capita (current US$)",
    "GDP per capita growth (annual %)",
    #"Poverty headcount ratio at national poverty lines (% of population)",
    #"School enrollment, primary (% net)",
    #"School enrollment, secondary (% net)",
    #"School enrollment, tertiary (% gross)",
    #"Educational attainment, at least completed primary, population 25+ years, total (%)",
    #"Educational attainment, at least completed secondary, population 25+ years, total (%)",
    #"Educational attainment, at least completed tertiary, population 25+ years, total (%)",
    #"Life expectancy at birth, total (years)",
    #"Poverty gap at $1.90 a day (PPP) (% of population)",
    "Population, total",
    "Population, female",
    "Population, female (% of total population)",
    "Population, male",
    "Population, male (% of total population)",
    "Compulsory education, duration (years)",
    "Government expenditure on education, total (% of GDP)",
    "Government expenditure on education, total (% of government expenditure)"

]

# Filtrar el DataFrame para incluir solo los indicadores relevantes
df_relevant = df[df['Indicator Name'].isin(indicadores_relevantes)]

# Mostrar las primeras filas del DataFrame filtrado
df_relevant.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
223,Africa Eastern and Southern,AFE,"Compulsory education, duration (years)",SE.COM.DURS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,NaN
366,Africa Eastern and Southern,AFE,Employment in agriculture (% of total employme...,SL.AGR.EMPL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.827249,58.266986,57.807498,57.314044,56.754459,56.164163,56.609981,56.376621,55.750775,NaN
369,Africa Eastern and Southern,AFE,Employment in industry (% of total employment)...,SL.IND.EMPL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.073648,10.200033,10.183006,10.189464,10.148490,10.041244,9.973415,9.943005,10.111156,NaN
372,Africa Eastern and Southern,AFE,Employment in services (% of total employment)...,SL.SRV.EMPL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.099104,31.532985,32.009498,32.496486,33.097052,33.794594,33.416602,33.680376,34.138069,NaN
478,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,0.254876,7.965827,5.148206,4.579317,5.346211,...,4.007577,2.965062,2.219015,2.571941,2.491355,2.040617,-2.799038,4.300441,3.435138,NaN

In [7]:
valores_unicos_df_relevant2022= df_relevant['Indicator Name'].unique()
valores_unicos_df_relevant2022

array(['Compulsory education, duration (years)',
       'Employment in agriculture (% of total employment) (modeled ILO estimate)',
       'Employment in industry (% of total employment) (modeled ILO estimate)',
       'Employment in services (% of total employment) (modeled ILO estimate)',
       'GDP growth (annual %)', 'GDP per capita (current US$)',
       'GDP per capita growth (annual %)',
       'Government expenditure on education, total (% of GDP)',
       'Government expenditure on education, total (% of government expenditure)',
       'Labor force, female (% of total labor force)',
       'Labor force, total', 'Population, female',
       'Population, female (% of total population)', 'Population, male',
       'Population, male (% of total population)', 'Population, total',
       'Unemployment with advanced education (% of total labor force with advanced education)',
       'Unemployment with basic education (% of total labor force with basic education)',
       'Unemployment with intermediate education (% of total labor force with intermediate education)',
       'Unemployment, total (% of total labor force) (modeled ILO estimate)',
       'Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)'],
      dtype=object)

In [8]:
df_relevant.values

array([['Africa Eastern and Southern', 'AFE',
        'Compulsory education, duration (years)', ..., 7.0, 7.0, nan],
       ['Africa Eastern and Southern', 'AFE',
        'Employment in agriculture (% of total employment) (modeled ILO estimate)',
        ..., 56.37662059383139, 55.75077488269868, nan],
       ['Africa Eastern and Southern', 'AFE',
        'Employment in industry (% of total employment) (modeled ILO estimate)',
        ..., 9.94300492327448, 10.111156355463933, nan],
       ...,
       ['Zimbabwe', 'ZWE',
        'Unemployment with intermediate education (% of total labor force with intermediate education)',
        ..., 11.589, nan, nan],
       ['Zimbabwe', 'ZWE',
        'Unemployment, total (% of total labor force) (modeled ILO estimate)',
        ..., 9.54, 9.256, 9.116],
       ['Zimbabwe', 'ZWE',
        'Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)',
        ..., 15.154, 14.802, 14.57]], dtype=object)

In [9]:
df_relevant.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023'],
      dtype='object')

In [10]:
df_relevant = df_relevant.rename(columns={'1960': 'Año 1960'})
df_relevant = df_relevant.rename(columns={'2022': 'Año 2022'})
df_relevant = df_relevant.rename(columns={'2023': 'Año 2023'})
df_relevant = df_relevant.rename(columns={'2021': 'Año 2021'})

In [11]:
df_relevant2022 = df_relevant[['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code','Año 2022']]

In [12]:
df_relevant2022

,Country Name,Country Code,Indicator Name,Indicator Code,Año 2022
223,Africa Eastern and Southern,AFE,"Compulsory education, duration (years)",SE.COM.DURS,7.000000
366,Africa Eastern and Southern,AFE,Employment in agriculture (% of total employme...,SL.AGR.EMPL.ZS,55.750775
369,Africa Eastern and Southern,AFE,Employment in industry (% of total employment)...,SL.IND.EMPL.ZS,10.111156
372,Africa Eastern and Southern,AFE,Employment in services (% of total employment)...,SL.SRV.EMPL.ZS,34.138069
478,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,3.435138
...,...,...,...,...,...
396811,Zimbabwe,ZWE,Unemployment with advanced education (% of tot...,SL.UEM.ADVN.ZS,NaN
396814,Zimbabwe,ZWE,Unemployment with basic education (% of total ...,SL.UEM.BASC.ZS,NaN
396817,Zimbabwe,ZWE,Unemployment with intermediate education (% of...,SL.UEM.INTM.ZS,NaN
396824,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,9.256000
396830,Zimbabwe,ZWE,"Unemployment, youth total (% of total labor fo...",SL.UEM.1524.ZS,14.802000

In [13]:
valores_unicos_df_relevant2022= df_relevant2022['Indicator Name'].unique()
valores_unicos_df_relevant2022

array(['Compulsory education, duration (years)',
       'Employment in agriculture (% of total employment) (modeled ILO estimate)',
       'Employment in industry (% of total employment) (modeled ILO estimate)',
       'Employment in services (% of total employment) (modeled ILO estimate)',
       'GDP growth (annual %)', 'GDP per capita (current US$)',
       'GDP per capita growth (annual %)',
       'Government expenditure on education, total (% of GDP)',
       'Government expenditure on education, total (% of government expenditure)',
       'Labor force, female (% of total labor force)',
       'Labor force, total', 'Population, female',
       'Population, female (% of total population)', 'Population, male',
       'Population, male (% of total population)', 'Population, total',
       'Unemployment with advanced education (% of total labor force with advanced education)',
       'Unemployment with basic education (% of total labor force with basic education)',
       'Unemployment with intermediate education (% of total labor force with intermediate education)',
       'Unemployment, total (% of total labor force) (modeled ILO estimate)',
       'Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)'],
      dtype=object)

In [14]:
xls_file_path = '/Users/luis/Desktop/00. UEV/Primero/00. Proyecto Análisis de Datos UE/Entrega 5/LimpiosBankWorld.xlsx'
df_relevant2022.to_excel(xls_file_path, sheet_name='Seleccionados', index=False)

In [15]:
# Pivotar el DataFrame para que los indicadores sean filas
df_pivotado = df_relevant2022.pivot_table(
    index=['Country Name', 'Country Code'],
    columns='Indicator Name',
    values='Año 2022'
).reset_index()

# Mostrar las primeras filas del DataFrame pivotado
df_pivotado.head()

Indicator Name,Country Name,Country Code,"Compulsory education, duration (years)",Employment in agriculture (% of total employment) (modeled ILO estimate),Employment in industry (% of total employment) (modeled ILO estimate),Employment in services (% of total employment) (modeled ILO estimate),GDP growth (annual %),GDP per capita (current US$),GDP per capita growth (annual %),"Government expenditure on education, total (% of GDP)",...,"Population, female","Population, female (% of total population)","Population, male","Population, male (% of total population)","Population, total",Unemployment with advanced education (% of total labor force with advanced education),Unemployment with basic education (% of total labor force with basic education),Unemployment with intermediate education (% of total labor force with intermediate education),"Unemployment, total (% of total labor force) (modeled ILO estimate)","Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)"
0,Afghanistan,AFG,9.0,46.589070,18.340073,35.070857,NaN,NaN,NaN,NaN,...,20362329.0,49.508722,20766442.0,50.491278,41128771.0,NaN,NaN,NaN,14.100000,17.841000
1,Africa Eastern and Southern,AFE,7.0,55.750775,10.111156,34.138069,3.435138,1644.062829,0.869269,3.906225,...,363834524.0,50.472347,357024605.0,49.527652,720859132.0,NaN,NaN,NaN,7.748144,13.960496
2,Africa Western and Central,AFW,9.0,45.091034,13.771124,41.137846,3.766354,1785.312219,1.196174,2.928443,...,243821774.0,49.725969,246509095.0,50.274031,490330870.0,NaN,NaN,NaN,3.809080,6.648333
3,Albania,ALB,9.0,34.926718,21.400145,43.673137,4.856402,6810.114041,6.139017,NaN,...,1392115.0,50.117738,1385573.0,49.882227,2777689.0,NaN,NaN,NaN,11.629000,28.200000
4,Algeria,DZA,10.0,9.743230,30.850998,59.405771,3.200002,4342.637968,1.533163,NaN,...,22040987.0,49.085532,22862237.0,50.914465,44903225.0,NaN,NaN,NaN,12.491000,32.007000

In [16]:
# Guardar el DataFrame pivotado en un archivo CSV
csv_file_path = '/Users/luis/Desktop/00. UEV/Primero/00. Proyecto Análisis de Datos UE/Entrega 5/df_pivotado_new.csv'
df_pivotado.to_csv(csv_file_path, index=False)

# Guardar el DataFrame pivotado en un archivo Excel
excel_file_path1 = '/Users/luis/Desktop/00. UEV/Primero/00. Proyecto Análisis de Datos UE/Entrega 5/df_pivotado_new.xlsx'

df_pivotado.to_excel(excel_file_path1, sheet_name='Pivotado', index=False)

In [17]:
df_pivotado.head(30)

Indicator Name,Country Name,Country Code,"Compulsory education, duration (years)",Employment in agriculture (% of total employment) (modeled ILO estimate),Employment in industry (% of total employment) (modeled ILO estimate),Employment in services (% of total employment) (modeled ILO estimate),GDP growth (annual %),GDP per capita (current US$),GDP per capita growth (annual %),"Government expenditure on education, total (% of GDP)",...,"Population, female","Population, female (% of total population)","Population, male","Population, male (% of total population)","Population, total",Unemployment with advanced education (% of total labor force with advanced education),Unemployment with basic education (% of total labor force with basic education),Unemployment with intermediate education (% of total labor force with intermediate education),"Unemployment, total (% of total labor force) (modeled ILO estimate)","Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)"
0,Afghanistan,AFG,9.0,46.589070,18.340073,35.070857,NaN,NaN,NaN,NaN,...,20362329.0,49.508722,20766442.0,50.491278,41128771.0,NaN,NaN,NaN,14.100000,17.841000
1,Africa Eastern and Southern,AFE,7.0,55.750775,10.111156,34.138069,3.435138,1644.062829,0.869269,3.906225,...,363834524.0,50.472347,357024605.0,49.527652,720859132.0,NaN,NaN,NaN,7.748144,13.960496
2,Africa Western and Central,AFW,9.0,45.091034,13.771124,41.137846,3.766354,1785.312219,1.196174,2.928443,...,243821774.0,49.725969,246509095.0,50.274031,490330870.0,NaN,NaN,NaN,3.809080,6.648333
3,Albania,ALB,9.0,34.926718,21.400145,43.673137,4.856402,6810.114041,6.139017,NaN,...,1392115.0,50.117738,1385573.0,49.882227,2777689.0,NaN,NaN,NaN,11.629000,28.200000
4,Algeria,DZA,10.0,9.743230,30.850998,59.405771,3.200002,4342.637968,1.533163,NaN,...,22040987.0,49.085532,22862237.0,50.914465,44903225.0,NaN,NaN,NaN,12.491000,32.007000
5,American Samoa,ASM,NaN,NaN,NaN,NaN,1.735016,19673.390102,3.486017,NaN,...,22399.0,50.592912,21873.0,49.404829,44273.0,NaN,NaN,NaN,NaN,NaN
6,Andorra,AND,10.0,NaN,NaN,NaN,8.809579,41992.772778,7.732716,2.666230,...,39038.0,48.905091,40786.0,51.094909,79824.0,NaN,NaN,NaN,NaN,NaN
7,Angola,AGO,6.0,56.318261,5.673967,38.007772,3.045403,3000.444231,-0.096755,2.332126,...,17998220.0,50.572443,17590767.0,49.427557,35588987.0,NaN,NaN,NaN,14.478000,28.009000
8,Antigua and Barbuda,ATG,11.0,NaN,NaN,NaN,9.516396,19919.726687,8.880997,3.563353,...,48981.0,52.239156,44782.0,47.760844,93763.0,NaN,NaN,NaN,NaN,NaN
9,Arab World,ARB,9.0,16.039159,24.581588,59.379253,6.033833,7625.252464,4.170905,NaN,...,224567216.0,48.326771,240117694.0,51.673228,464684914.0,NaN,NaN,NaN,10.732883,27.060454
10,Argentina,ARG,14.0,7.205906,19.954905,72.839190,4.956370,13650.604629,3.989131,NaN,...,23345532.0,50.493387,22889298.0,49.506613,46234830.0,2.898,7.777,8.295,6.805000,18.979000
11,Armenia,ARM,12.0,52.416223,14.038897,33.544879,12.600000,7018.051504,13.025419,2.493270,...,1530390.0,55.040714,1250079.0,44.959286,2780469.0,NaN,NaN,NaN,8.588000,19.015000
12,Aruba,ABW,13.0,NaN,NaN,NaN,10.458317,33300.838819,10.553786,NaN,...,56272.0,52.864860,50173.0,47.135140,106445.0,NaN,NaN,NaN,NaN,NaN
13,Australia,AUS,10.0,2.199554,18.636642,79.163804,4.268946,65099.845912,2.985396,NaN,...,13092536.0,50.345181,12913005.0,49.654823,26005540.0,NaN,NaN,NaN,3.700000,8.233000
14,Austria,AUT,13.0,3.538558,26.364178,70.097241,4.806430,52084.681195,3.808956,NaN,...,4590312.0,50.767387,4451539.0,49.232613,9041851.0,3.490,12.417,4.241,4.990000,10.350000
15,Azerbaijan,AZE,10.0,35.622490,14.916797,49.460732,4.616523,7762.073829,4.575199,2.904259,...,5137643.0,50.658317,5004112.0,49.341673,10141756.0,5.110,12.310,5.130,5.650000,13.583000
16,"Bahamas, The",BHS,12.0,3.039179,11.785448,85.174907,14.368210,31458.300812,13.788536,2.948463,...,214167.0,52.237892,195817.0,47.762108,409984.0,NaN,NaN,NaN,10.089000,25.139000
17,Bahrain,BHR,9.0,0.900849,34.817579,64.281572,4.860858,30146.925026,4.222106,1.987460,...,560034.0,38.039767,912199.0,61.960233,1472233.0,NaN,NaN,NaN,1.339000,5.894000
18,Bangladesh,BGD,5.0,36.858216,21.878955,41.262829,7.099829,2688.305501,5.954845,1.972786,...,86327159.0,50.428757,84859213.0,49.571243,171186372.0,12.161,4.527,8.082,4.271000,12.541000
19,Barbados,BRB,11.0,2.724859,16.510104,80.765788,11.333740,20238.784242,11.161779,4.508760,...,146550.0,52.035436,135084.0,47.964209,281635.0,NaN,NaN,NaN,8.501000,26.096000
20,Belarus,BLR,11.0,10.630982,30.357774,59.011223,-4.697450,7888.263711,-3.927909,NaN,...,4979107.0,53.956097,4248965.0,46.043914,9228071.0,2.368,10.649,4.070,3.570000,10.269000
21,Belgium,BEL,12.0,0.907771,19.065373,80.026836,3.009903,49926.825430,2.131766,NaN,...,5911748.0,50.589099,5774066.0,49.410901,11685814.0,3.097,12.740,6.320,5.560000,16.441000
22,Belize,BLZ,8.0,16.784996,19.573423,63.641581,8.734311,6984.216960,7.328153,4.473050,...,201525.0,49.725863,203747.0,50.274137,405272.0,NaN,NaN,NaN,8.672000,17.926000
23,Benin,BEN,6.0,28.386114,22.290290,49.323575,6.253245,1302.851036,3.420679,3.210927,...,6663569.0,49.903669,6689295.0,50.096331,13352864.0,NaN,NaN,NaN,1.476000,3.931000
24,Bermuda,BMU,13.0,NaN,NaN,NaN,2.927113,118774.790657,3.302972,1.922213,...,32917.0,51.811978,30615.0,48.188022,63532.0,NaN,NaN,NaN,NaN,NaN
25,Bhutan,BTN,NaN,43.955610,15.239736,40.804404,NaN,NaN,NaN,8.141788,...,368525.0,47.098555,413930.0,52.901445,782455.0,12.004,5.161,17.649,5.950000,29.608000
26,Bolivia,BOL,14.0,27.020188,20.550600,52.429195,3.605680,3600.121635,2.379798,NaN,...,6097747.0,49.882953,6126364.0,50.117056,12224110.0,5.148,2.477,4.917,3.552000,6.265000
27,Bosnia and Herzegovina,BIH,9.0,16.872603,33.485071,49.642326,4.106227,7568.798480,5.310900,NaN,...,1641713.0,50.771604,1591814.0,49.228427,3233526.0,10.491,16.087,13.058,12.660000,31.893000
28,Botswana,BWA,NaN,17.638357,15.700083,66.661446,5.787917,7738.878804,4.103826,NaN,...,1331489.0,50.621261,1298807.0,49.378739,2630296.0,18.482,25.352,29.526,23.620000,43.523000
29,Brazil,BRA,14.0,8.731441,20.491703,70.776857,2.900531,8917.674911,2.428702,NaN,...,109580471.0,50.893452,105733027.0,49.106548,215313498.0,5.064,11.877,10.415,9.230000,20.679000